export const TEAMS = [
  // UEFA (16)
  { name: "France", flag: "🇫🇷" },
  { name: "Angleterre", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Espagne", flag: "🇪🇸" },
  { name: "Allemagne", flag: "🇩🇪" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Pays-Bas", flag: "🇳🇱" },
  { name: "Italie", flag: "🇮🇹" },
  { name: "Belgique", flag: "🇧🇪" },
  { name: "Autriche", flag: "🇦🇹" },
  { name: "Danemark", flag: "🇩🇰" },
  { name: "Suisse", flag: "🇨🇭" },
  { name: "Turquie", flag: "🇹🇷" },
  { name: "Albanie", flag: "🇦🇱" },
  { name: "Slovaquie", flag: "🇸🇰" },
  { name: "Ukraine", flag: "🇺🇦" },
  { name: "Suède", flag: "🇸🇪" },
  // CONMEBOL (6)
  { name: "Argentine", flag: "🇦🇷" },
  { name: "Brésil", flag: "🇧🇷" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "Colombie", flag: "🇨🇴" },
  { name: "Équateur", flag: "🇪🇨" },
  { name: "Venezuela", flag: "🇻🇪" },
  // CAF (9)
  { name: "Maroc", flag: "🇲🇦" },
  { name: "Sénégal", flag: "🇸🇳" },
  { name: "Nigéria", flag: "🇳🇬" },
  { name: "Afrique du Sud", flag: "🇿🇦" },
  { name: "Côte d'Ivoire", flag: "🇨🇮" },
  { name: "Égypte", flag: "🇪🇬" },
  { name: "Cameroun", flag: "🇨🇲" },
  { name: "RD Congo", flag: "🇨🇩" },
  { name: "Algérie", flag: "🇩🇿" },
  // AFC (8)
  { name: "Japon", flag: "🇯🇵" },
  { name: "Corée du Sud", flag: "🇰🇷" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Arabie Saoudite", flag: "🇸🇦" },
  { name: "Australie", flag: "🇦🇺" },
  { name: "Indonésie", flag: "🇮🇩" },
  { name: "Jordanie", flag: "🇯🇴" },
  { name: "Ouzbékistan", flag: "🇺🇿" },
  // CONCACAF — pays hôtes (3)
  { name: "USA", flag: "🇺🇸" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Mexique", flag: "🇲🇽" },
  // CONCACAF — qualifiés (6)
  { name: "Panama", flag: "🇵🇦" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "Haïti", flag: "🇭🇹" },
  { name: "Jamaïque", flag: "🇯🇲" },
  { name: "Guatemala", flag: "🇬🇹" },
];
