export const TEAMS = [
  { name: "France", flag: "🇫🇷" },
  { name: "Brésil", flag: "🇧🇷" },
  { name: "Argentine", flag: "🇦🇷" },
  { name: "Angleterre", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Espagne", flag: "🇪🇸" },
  { name: "Allemagne", flag: "🇩🇪" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Maroc", flag: "🇲🇦" },
  { name: "Sénégal", flag: "🇸🇳" },
  { name: "USA", flag: "🇺🇸" },
  { name: "Mexique", flag: "🇲🇽" },
  { name: "Japon", flag: "🇯🇵" },
  { name: "Pays-Bas", flag: "🇳🇱" },
  { name: "Colombie", flag: "🇨🇴" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "Croatie", flag: "🇭🇷" },
  { name: "Belgique", flag: "🇧🇪" },
  { name: "Danemark", flag: "🇩🇰" },
  { name: "Suisse", flag: "🇨🇭" },
  { name: "Australie", flag: "🇦🇺" },
  { name: "Corée du Sud", flag: "🇰🇷" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Pologne", flag: "🇵🇱" },
  { name: "Serbie", flag: "🇷🇸" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Cameroun", flag: "🇨🇲" },
  { name: "Tunisie", flag: "🇹🇳" },
  { name: "Côte d'Ivoire", flag: "🇨🇮" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "Afrique du Sud", flag: "🇿🇦" },
  { name: "Équateur", flag: "🇪🇨" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Pérou", flag: "🇵🇪" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "Paraguay", flag: "🇵🇾" },
  { name: "Bolivie", flag: "🇧🇴" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "Arabie Saoudite", flag: "🇸🇦" },
  { name: "Ouzbékistan", flag: "🇺🇿" },
  { name: "Indonésie", flag: "🇮🇩" },
  { name: "Nouvelle-Zélande", flag: "🇳🇿" },
  { name: "Slovaquie", flag: "🇸🇰" },
  { name: "Albanie", flag: "🇦🇱" },
  { name: "Autriche", flag: "🇦🇹" },
  { name: "Hongrie", flag: "🇭🇺" },
  { name: "Ukraine", flag: "🇺🇦" },
  { name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { name: "Tchéquie", flag: "🇨🇿" },
];
